[project]
name = "ftir_data_analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib",
    "scipy>=1.14.0",
]
